### ISSUE TITLE
Allow multi-selection/multi-editing

### ISSUE THREAD

**Issue by mmyers** [mmyers/eug#23]
[Hjalfnar writes:](https://forum.paradoxplaza.com/forum/index.php?threads/announcing-a-scenario-editor-and-map-viewer.707474/page-37#post-23221922)

> Is it possible to edit multiple provinces at once? I have a HUGE load of provinces to work on (CK2 save export) and to edit every single one of them would be incredible tiresome...

> Province owner, controller, culture, religion, core. The HoI3PosEd had the option to select multiple provinces and then only showed the things they had in common, which allowed you to edit multiple provinces at once. It only took \[me\] a load of klicks and 5 minutes to edit in the complete Ukraine.

**Comment by mmyers** [comment]
Closed in f75c92e1484b37c0b43d02151a3f750ae426681f

**Comment by madprogramer** [comment]
Not to take credit but I'm glad to have pinged you over Discord about this :). I guess sometimes all you need is someone to cheer you on!

**Comment by mmyers** [comment]
> Not to take credit but I'm glad to have pinged you over Discord about this :). I guess sometimes all you need to get the job done is someone to cheer you on!

That's exactly what it takes. This editor gets thousands of downloads but no engagement. Meanwhile, For the Glory has tens of players, but they're all in Discord. Guess which project I prefer working on?
