### ISSUE TITLE
Absolute Paths in the "path=x" portion of an EU4 .mod file break the program

### ISSUE THREAD

**Issue by theolaa** [mmyers/eug#28]
More or less the title. This line here
![image](https://user-images.githubusercontent.com/38194309/125916207-72b194fd-960b-4a2b-818b-6289f0a4ce19.png)
in Main.java should check to see if the path is absolute, and if it is, convert it to the relative path that the rest of the program expects.
Unfortunately, the solution isn't as simple as "just using a relative path in the descriptor", since mods created through the launcher are sometimes automatically created with an absolute path - with no way to change it.

**Comment by mmyers** [comment]
Good catch, thanks!
