### ISSUE TITLE
Adding a city

### ISSUE THREAD

**Issue by IanTrudel** [mmyers/eug#37]
Fantastic tools!

I am trying to add a city, which the Positions Editor made easy, but the question is now: How can I associate the new position to the new city (name, population, etc.)?

**Comment by mmyers** [comment]
What game are you working with? In most Paradox games, you'll need to make a history file for the province to set the city name and population (you can use the my scenario editor to do it easily). In Victoria 2, you also need a pop history file.

**Comment by IanTrudel** [comment]
In Victoria II, indeed. Some cities are established at a later date. Could you please provide an example? I searched existing mods but they have so many files.

**Comment by mmyers** [comment]
To change the name later in the history, I believe you would need a block like this:

```
1870.1.1 = {
    name = "New City Name"
}
```

Pop modding is covered pretty well by the wiki: https://vic2.paradoxwikis.com/Population_modding

I don't currently have support for editing pops, but you can still use the editor to view them quickly without having to reload the game. The pop mapmodes show the majority in the province and then you can hover over the province to get a full list of the pops.
